sudo: false
language: python
services:
  - redis
python:
  - "2.6"
  - "2.7"
  - "pypy"
install:
  - pip install -e .
  - pip install pytest-cov
  - pip install coveralls
  #- pip install pytest  # installed by Travis by default already
script:
    py.test --cov tests --durations=5
